Netflix/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *
app_name='app'
urlpatterns=[
    path('index/',index,name='index'),
    path('',login,name='login'),
    path('logout/',logout,name='logout'),
    path('signup/',signup,name='signup'),
    path('search/',search,name='search'),
    path('my_list/',my_list,name='my_list'),
    path('movie/<str:pk>',movie,name='movie'),
    path('genre/<str:pk>',genre,name='genre'),
    path('add_to_list/',add_to_list,name='add_to_list')
]

app/models.py
from django.db import models
import uuid
from django.conf import settings
# Create your models here.
class Genre(models.Model):
    GENRE_CHOICES = models.CharField(primary_key =True,max_length=100)

    def __str__(self):
        return self.GENRE_CHOICES
    
class Movie(models.Model):

    uu_id = models.UUIDField(default=uuid.uuid4)
    title = models.CharField(max_length=250)
    description = models.TextField()
    release_date = models.DateField()
    genre = models.ForeignKey(Genre,on_delete=models.CASCADE)   
    length = models.PositiveIntegerField()
    image_card = models.ImageField(upload_to='movie_images/') 
    image_cover = models.ImageField(upload_to='movie_images/') 
    video = models.FileField(upload_to='movie_videos/')
    movie_views = models.IntegerField(default=0)

    def __str__(self):
        return self.title
    
class Movielist(models.Model):
    owner_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    

app/views.py
import re
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from django.contrib import auth
from .models import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

# Create your views here.
@login_required(login_url='/')
def index(request):
    gen=Genre.objects.all()
    movies = Movie.objects.all()
    context = {'movies':movies,'genre':gen}
    return render(request,'index.html',context)



def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user and user.is_active: 
            auth.login(request,user)
            return redirect('/index')
        else:
            messages.info(request,'Credentials Invalid !!')
            return redirect('/')
    return render(request,'login.html')

@login_required(login_url='/')
def logout(request):
    auth.logout(request)
    return redirect('/')

@login_required(login_url='/')
def movie(request,pk):
    movie_uuid = pk
    gen = Genre.objects.all()
    movie_details = Movie.objects.get(uu_id=movie_uuid)
    context = {'movie_details':movie_details,'genre':gen}

    return render(request,'movie.html',context)


def signup(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            if User.objects.filter(email=email).exists():
                messages.info(request,'Email alrady taken')
                return redirect('/signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request,'Username alrady taken')
                return redirect('/signup')
            else:
                user =User.objects.create_user(username=username,email=email,password=password)
                user.save()
                
                return redirect('/')
                
        else:
            messages.info(request,'Password is Not Matching')
            return redirect('/signup')
        
    else:
        return render(request,'signup.html')



@login_required(login_url='/')
def my_list(request):
    gen = Genre.objects.all()
    MO = Movielist.objects.filter(owner_user=request.user)
    AMO = []
    for i in MO:
        AMO.append(i.movie)
   
    return render(request,'my_list.html',{'movies':AMO,'genre':gen})

@login_required(login_url='/')
def search(request):
    gen = Genre.objects.all()
    if request.method == 'POST':
        search_term = request.POST['search_term']
        movies = Movie.objects.filter(title__icontains=search_term)
        context = {'movies':movies,"search_term":search_term,'genre':gen}
    
        return render(request,'search.html',context)
    else:
        return redirect('app/index',{'genre':gen})

@login_required(login_url='/')
def genre(request,pk):
    movie_genre = pk
    gen = Genre.objects.all()
    movies = Movie.objects.filter(genre=movie_genre)
    context = {'movies':movies,"movie_genre":movie_genre,'genre':gen}
    return render(request,'genre.html',context)

def add_to_list(request):
    if request.method == 'POST':
        movie_url_id = request.POST.get('movie_id')
        uuid_pattern = r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
        match = re.search(uuid_pattern,movie_url_id)
        movie_id = match.group() if match else None
        movie = get_object_or_404(Movie,uu_id=movie_id)
        movie_list, created = Movielist.objects.get_or_create(owner_user=request.user,movie=movie) 
        movie_list.save()     
        if created:
            response_data = {'status':'success','message':'Added'}
        else:
            response_data = {'status':'info','message':'Movie already in list'}
        return JsonResponse(response_data)
    else:
        return JsonResponse({'status':'error','message':'Invalid request'},status=400)

templates/genre.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        .footer{
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #141414;
            text-align: center;
            display: flex;
            justify-content: center;
            justify-items: center;
        }
        .footer .footer-iconTop{
            margin-left: 1rem;
        }
        
        .gentitle::first-letter{
            text-transform: capitalize;
        }
        #dropdownMenu{
            background-color:black;
            
        }
        #dropdownMenu a{
            color: aliceblue;
        }
    </style>
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="{% url 'app:index' %}"><i class="fa-solid fa-house"></i></i> Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer"><i class="fa-solid fa-user-gear"></i> Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    {% for Genre in genre  %}
                    <ul><a class="gentitle" href="{% url 'app:genre' Genre %}">{{Genre}}</a></ul>
                    {% endfor %}
                    
                    
                </div>
            </div>

            <span><a href="{% url 'app:my_list' %}"><i class="fa-solid fa-list"></i> My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center">
            <form action="{% url 'app:search' %}" method="POST">
                {% csrf_token %}
                <input type="search" name="search_term" placeholder="Search" class="bg-gray-700 p-2 rounded">
                <button type="submit" class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome, {{user.username}}</a>
                <a href="{% url 'app:logout' %}" class="block p-2">Logout</a>
            </div>
        </div>
    </header>
    
    <hr>

    <section class="py-10 px-5">
    
        <div align="center">
            <h2 class="text-xl mb-5">
                '{{movie_genre | title}}' Movie
            </h2>
        </div>
        <div class="flex space-x-5 flex-wrap justify-center">

            {% for movie in movies %}
            <div class="w-40 m-3 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center;">
            </div>
            {% endfor %}
        </div>
    </section>
    
   

    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img  width="100%" height="100%" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="/movie/{{ movie.uu_id }}">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <button id="addToListButton" onclick="addItemToList()"  class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
            
        </div>
    </div>

    <!-- footer  -->
    <div class="footer">
        <div class="footer-text">
            <p>Copyright &copy; 2024 by Krishnamohan Singh | All Rights Reserved.</p>
        </div>

        <div class="footer-iconTop">
            <a href="#"><i class="fa-solid fa-arrow-up"></i></i></a>
        </div>
    </div>

    <script>
        function showModal(element) {
            // Retrieve data attributes
            const title = element.getAttribute('data-title');
            const description = element.getAttribute('data-description');
            const releaseDate = element.getAttribute('data-release-date');
            const genre = element.getAttribute('data-genre');
            const length = element.getAttribute('data-length');
            const imageCardUrl = element.getAttribute('data-image-card-url');
            const imageCoverUrl = element.getAttribute('data-image-cover-url');
            const dataVideoUrl = element.getAttribute('data-video-url');
        
            // Update the modal's content with the movie details
            const modal = document.getElementById('movieModal');
            modal.querySelector('.modal-content h2').textContent = title;
            modal.querySelector('.modal-content img').src = imageCoverUrl;
            modal.querySelector('.modal-content a').href = dataVideoUrl;  
            modal.querySelector('.modal-content img').alt = title + " Cover Image";
            modal.querySelector('.modal-content .flex span:first-child').textContent = "Year: " + releaseDate;
            modal.querySelector('.modal-content .flex span:nth-child(2)').textContent = "Genre: " + genre;
            modal.querySelector('.modal-content .flex span:last-child').textContent = "Length: " + length + "min";
            modal.querySelector('.modal-content p').textContent = description;
        
            // Show the modal
            modal.style.display = 'block';
            setTimeout(() => {
                modal.classList.add('modal-show');
            }, 50);
        }
        
        function hideModal() {
            const modal = document.querySelector('.modal');
            modal.classList.remove('modal-show');
            setTimeout(() => {
                modal.style.display = 'none';
            }, 300);
        }
        

        window.onclick = function(event) {
            if (event.target === document.getElementById('movieModal')) {
                hideModal();
            }
        }
        
        function addItemToList(){
            const modal = document.getElementById('movieModal')
            var movieID = modal.querySelector('.modal-content a').href;
            console.log(movieID)
            $.ajax({
                url: "{% url 'app:add_to_list' %}",
                type: "POST",
                data: {
                    movie_id: movieID,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success: function(data) {
                    $('#addToListButton').text(data.message);

                    $('#addToListButton').prop('disabled', true);

                    console.log("Item added to list!");
                },
                error: function(xhr, errmsg, err) {
                    
                    console.error("Error adding item to list: " + errmsg);
                }
            });
        }
        
        
    </script>
</body>

</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone</title>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
   
    <style>
     #index-main{
           
            top: 0%;
            
        } 
        .netflix-home-video{
            
            width: 100%;
            position: absolute;
            top: 0%;
            z-index: -1;
            height: 350px;
        }
        .netflix-home-video video{
            width: 100%;
        
        }
        .movie{
            margin-top: 38%;
        }
        footer{
            height: 4rem;
            background-color:#141414;
            display: flex;
            justify-items: center;
           justify-content: center;
        }
        footer .footer-text,.footer-iconTop{
            margin: 1rem;
            
        }
        .gentitle::first-letter{
            text-transform: capitalize;
        }
        #dropdownMenu{
            background-color:black;
            
        }
        #dropdownMenu a{
            color: aliceblue;
        }

    </style>
</head>

<body class="text-white" style="background-color: #141414;">
    <header class="p-5 flex justify-between items-center" id="index-main">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        
        
        <nav class="flex space-x-5">
            <span><a href="{% url 'app:index' %}"><i class="fa-solid fa-house"></i></i> Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer"><i class="fa-solid fa-user-gear"></i> Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    {% for Genre in genre  %}
                    <ul><a class="gentitle" href="{% url 'app:genre' Genre %}"> {{Genre}}</a></ul>
                    {% endfor %}
                </div>
            </div>

            <span><a href="{% url 'app:my_list' %}"><i class="fa-solid fa-list"></i> My List</a></span>
        </nav>


        <div class="flex space-x-5 items-center" id="search">
            <form action="{% url 'app:search' %}" method="POST">
                {% csrf_token %}
                <input type="search" name="search_term" placeholder="Search" class="bg-gray-700 p-2 rounded">
                <button type="submit" class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="#" class="block p-2">Welcome, {{user.username}}</a>  
                <a href="{% url 'app:logout' %}" class="block p-2">Logout</a>
            </div>
        </div>

       
    </header>

    <div class="">
        <section class="netflix-home-video">
            <video src="{% static 'video/titanic.mp4' %}" autoplay muted loop>No video</video> 
        </section>
    </div>
    

    <section class="py-10 px-5 movie" >
    
        <h2 class="text-xl mb-5">Popular on Netflix</h2>
        <div class="flex flex-wrap justify-center ">

            {% for movie in movies %}
            <div class="w-40 m-4 h-64 flex-shrink-0 film-card"
                onclick="showModal(this)" 
                data-title="{{ movie.title }}"
                data-description="{{ movie.description }}"
                data-release-date="{{ movie.release_date|date:'Y' }}"
                data-genre="{{ movie.get_genre_display }}" 
                data-length="{{ movie.length }}"
                data-image-card-url="{{ movie.image_card.url }}"
                data-image-cover-url="{{ movie.image_cover.url }}"
                data-video-url="/movie/{{ movie.uu_id }}"
                style="background-image: url('{{movie.image_card.url}}'); background-size: cover; background-position: center;">
            </div>
            {% endfor %}
        </div>
    </section>
    
    <!-- Modal -->
    <div class="modal" id="movieModal">
        <div class="modal-content">
            <div class="flex justify-between">
                <h2 class="text-xl mb-5">Movie Title</h2>
                <button onclick="hideModal()">X</button>
            </div>
            <img width="100%" height="100%" src="https://bloximages.newyork1.vip.townnews.com/newsrecord.org/content/tncms/assets/v3/editorial/8/1e/81ea500c-45ac-11ee-a11e-a7402910a7e7/64ecaae69243a.image.jpg" alt="Movie Image" class=" mb-5">
            <div class="flex justify-between mb-5">
                <span>Year: 2023</span>
                <span>Length: 2h 15min</span>
            </div>
            <p class="mb-5">Detailed information about the movie.</p>
            <div class="flex space-x-4 mb-5">
                <a href="/movie/{{ movie.uu_id }}">
                    <button class="bg-red-600 text-white p-2 px-5 rounded hover:bg-red-500">Play</button>
                </a>
                <button id="addToListButton" onclick="addItemToList()"  class="border border-white text-white p-2 px-5 rounded hover:bg-gray-700">
                    Add to List
                </button>
            </div>
            
        </div>
    </div>

    <footer class="footer">
        <div class="footer-text">
            <p>Copyright &copy; 2024 by Krishnamohan Singh | All Rights Reserved.</p>
        </div>

        <div class="footer-iconTop">
            <a href="#"><i class="fa-solid fa-arrow-up"></i></i></a>
        </div>
    </footer>

    <script>
        function showModal(element) {
            // Retrieve data attributes
            const title = element.getAttribute('data-title');
            const description = element.getAttribute('data-description');
            const releaseDate = element.getAttribute('data-release-date');
            const genre = element.getAttribute('data-genre');
            const length = element.getAttribute('data-length');
            const imageCardUrl = element.getAttribute('data-image-card-url');
            const imageCoverUrl = element.getAttribute('data-image-cover-url');
            const dataVideoUrl = element.getAttribute('data-video-url');
        
            // Update the modal's content with the movie details
            const modal = document.getElementById('movieModal');
            modal.querySelector('.modal-content h2').textContent = title;
            modal.querySelector('.modal-content img').src = imageCoverUrl;
            modal.querySelector('.modal-content a').href = dataVideoUrl;  
            modal.querySelector('.modal-content img').alt = title + " Cover Image";
            modal.querySelector('.modal-content .flex span:first-child').textContent = "Year: " + releaseDate;
            modal.querySelector('.modal-content .flex span:nth-child(2)').textContent = "Genre: " + genre;
            modal.querySelector('.modal-content .flex span:last-child').textContent = "Length: " + length + "min";
            modal.querySelector('.modal-content p').textContent = description;
        
            // Show the modal
            modal.style.display = 'block';
            setTimeout(() => {
                modal.classList.add('modal-show');
            }, 50);
        }
        
        function hideModal() {
            const modal = document.querySelector('.modal');
            modal.classList.remove('modal-show');
            setTimeout(() => {
                modal.style.display = 'none';
            }, 300);
        }
        

        window.onclick = function(event) {
            if (event.target === document.getElementById('movieModal')) {
                hideModal();
            }
        }
        
        function addItemToList(){
            const modal = document.getElementById('movieModal')
            var movieID = modal.querySelector('.modal-content a').href;
            console.log(movieID)
            $.ajax({
                url: "{% url 'app:add_to_list' %}",
                type: "POST",
                data: {
                    movie_id: movieID,
                    csrfmiddlewaretoken: "{{ csrf_token }}"
                },
                success: function(data) {
                    $('#addToListButton').text(data.message);

                    $('#addToListButton').prop('disabled', true);

                    console.log("Item added to list!");
                },
                error: function(xhr, errmsg, err) {
                    
                    console.error("Error adding item to list: " + errmsg);
                }
            });
        }
        
        
    </script>
</body>

</html>

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/login.css' %}" />
    <style>
        body{
            background-image: url('{% static "img/netflix1.png" %}');
            background-size: cover;
        }
        h5{
            color: red;
        }
    </style>
    
</head>
<body>

    <div class="bg-image" >
        <div class="signup-container">
            <h1>Login</h1>
            <h2>Unlimited movies, TV shows, and more.</h2>

            <div>
                
                {% for message in messages %}
                <h5>{{message}}</h5>
                {% endfor %}
            </div>


            <form action="" method="POST">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username" />
                <input type="password" name="password" placeholder="Password" />
                <button style="color:white" type="submit" class="signup-btn">Login</button>
            </form>
            <div class="help-text" align="center">
                <span>Ready to watch? Enter your email to create or restart your membership.</span>
                <br>
                <br>
                <span>Dont have an account? <a href="{% url 'app:signup' %}">Signup</a></span>
            </div>
        </div>
    </div>

</body>
</html>

templates/movie.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Clone|| {{movie_details.title}}</title>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        .footer{
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #141414;
            text-align: center;
            display: flex;
            justify-content: center;
            justify-items: center;
        }
        .footer .footer-iconTop{
            margin-left: 1rem;
        }
        #dropdownMenu{
            background-color:black;
            
        }
        #dropdownMenu a{
            color: aliceblue;
        }
    </style>
</head>

<body class="bg-blue-900 text-white" style="background-color: #181818;">

    <!-- Navbar -->
    <header class="p-5 flex justify-between items-center">
        <img src="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png" height="30" alt="Netflix Logo" width="110">
        <nav class="flex space-x-5">
            <span><a href="{% url 'app:index' %}"><i class="fa-solid fa-house"></i></i> Home</a></span>
            
            <div class="dropdown">
                <span id="dropdownMenuButton" class="cursor-pointer"><i class="fa-solid fa-user-gear"></i> Genres ▼</span>
                
                <div id="dropdownMenu" class="dropdown-content hidden">
                    {% for Genre in genre  %}
                    <ul><a href="{% url 'app:genre' Genre %}"> {{Genre}}</a></ul>
                    {% endfor %}
                </div>
            </div>

            <span><a href="{% url 'app:my_list' %}"><i class="fa-solid fa-list"></i> My List</a></span>
        </nav>
        <div class="flex space-x-5 items-center">
            <form action="{% url 'app:search' %}" method="POST">
                {% csrf_token %}
                <input type="search" name="search_term" placeholder="Search" class="bg-gray-700 p-2 rounded">
                <button type="submit" class="bg-red-600 text-white p-2 rounded hover:bg-red-500">Search</button>
            </form>
            <div class="relative">
                <a href="{% url 'app:logout' %}" class="block p-2">Logout</a>
            </div>
        </div>
    </header>

    <hr>
    <!-- Main Content -->
    <div class="container mx-auto mt-10">
        <!-- Movie Title and Back Button -->
        <div class="flex items-center justify-between">
            <h2 class="text-3xl font-semibold">{{movie_details.title}}</h2>
            <a href="{% url 'app:index' %}" class="text-gray-400 hover:text-white">← Back to movies</a>
        </div>

        <div class="mt-8">
            <video class="w-full h-auto" controls>
                <source src="{{movie_details.video.url}}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </div>


        <!-- Movie Description -->
        <div class="mt-6">
            <h3 class="text-xl font-semibold mb-2">About the Movie</h3>
            <p>
                {{movie_details.description}}
            </p>
        </div>
    </div>

    <footer class="footer">
        <div class="footer-text">
            <p>Copyright &copy; 2024 by Krishnamohan Singh | All Rights Reserved.</p>
        </div>

        <div class="footer-iconTop">
            <a href="#"><i class="fa-solid fa-arrow-up"></i></i></a>
        </div>
    </footer>

</body>

</html>

templates/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Signup</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/login.css' %}" />
    
    
    <style>
        body{
            background-image: url('{% static "img/netflix1.png" %}');
            background-size: cover;
        }
        h5{
            color: red;
        }
    </style>
</head>
<body>

    <div class="bg-image">
        <div class="signup-container">
            <h1>Signup</h1>
            <h2>Unlimited movies, TV shows, and more.</h2>

            <div>
                
                {% for message in messages %}
                <h5>{{message}}</h5>
                {% endfor %}
            </div>

            <form action="" method="POST">
                {% csrf_token %}
                <input type="email" name="email" placeholder="Email address" />
                <input type="text" name="username" placeholder="Username" />
                <input type="password" name="password" placeholder="Password" />
                <input type="password" name="password2" placeholder="Repeat Password" />
                <button style="color:white" type="submit" class="signup-btn">Get Started ></button>
            </form>
            <div class="help-text" align="center">
                <span>Ready to watch? Enter your email to create or restart your membership.</span>
                <br>
                <br>
                <span>Already have an account? <a href="{% url 'app:login' %}">Login</a></span>
            </div>
        </div>
    </div>

</body>
</html>